### ISSUE TITLE
BItwise support

### ISSUE THREAD

**Issue by narrowtux** [narrowtux/abacus#1]
- [x] Bitshift `>>` `<<`
 - [x] `&` `|` `|^` `~` (`and` `or` `xor` `not`)

# TODO

 - [x] Parse to AST
 - [x] Write eval code
 - [x] Write formatter
 - [ ] Test all 3
