### ISSUE TITLE
Design unit system

### ISSUE THREAD

**Issue by narrowtux** [narrowtux/abacus#2]
#TODO

 - [ ] Registry for unit strings to their definitions
    - [ ] Possibility to use aliases (for example `meter` to `m`)
 - [ ] Prepare lexer and parser to parse unit expressions
    - `m / s` should be parsed as `{:divide, {:unit, "m"}, {:unit, "s"}}`
 - [ ] Add second parser-pass to map `{:unit, binary}` to a unit definition
 - [ ] Change `eval/2` functions to support multiplication operations (`/`, `*`, `^`) on amounts
 - [x] Support SI prefixes (`m`, `k`, `M`, ...)
 - [ ] function to convert units
